module.exports={
    baseUrl:'https://patient-dev.geton-institut.com/en',
    isHeadless:false,
    slowMo:0,
    isDevtools:false,
    launchTimeout:10000,
    waitingTimeout:10000,
    viewRepotWidth:800,
    viewRepotHeight:600
}